[".oh-my-zsh"]
    type = "archive"
    url = "https://github.com/ohmyzsh/ohmyzsh/archive/master.tar.gz"
    exact = true
    stripComponents = 1
    refreshPeriod = "168h"
[".oh-my-zsh/custom/plugins/fzf-tab"]
    type = "archive"
    url = "https://github.com/Aloxaf/fzf-tab/archive/master.tar.gz"
    exact = true
    stripComponents = 1
    refreshPeriod = "168h"
["Code/caelestia"]
    type = "git-repo"
    url = "https://github.com/caelestia-dots/caelestia.git"
    refreshPeriod = "168h"